services: docker
sudo: required
dist: trusty
language: ruby
rvm:
  - 2.3.3
script:
  - BEAKER_debug=true PUPPET_INSTALL_TYPE=agent bundle exec rake beaker
env:
  - BEAKER_set=docker/centos-7
  - BEAKER_set=docker/debian-7
  - BEAKER_set=docker/ubuntu-1404
